---
title: Julia Hallmark Christian Fiction
description: Where faith is explored in stories told, and anything is possible!
logo: images/logo.png
max_logo_height: 80
url: https://juliahallmark.com
homepage_greeting: Welcome!
newsletter: ''
advanced_footer_html: ''
timezone: America/Los_Angeles
permalink: /blog/:year-:month-:day_:title:output_ext
sass:
  sass_dir: _sass
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
collections:
  books:
    output: true
    style: compressed
exclude:
- src
