---
title: Julia Hallmark Christian Fiction
description: Where faith is explored in stories told, and anything is possible!
logo: images/logo.png
max_logo_height: 80
url: https://juliahallmark.com
homepage_greeting: Welcome!
newsletter: ''
advanced_footer_html: ''
timezone: America/Los_Angeles
permalink: /blog/:year-:month-:day_:title:output_ext
vendors:
  Facebook:
    name: Facebook
    icon: "/images/icons/facebook-icon.png"
  Amazon:
    name: Amazon.com
    icon: "/images/icons/amazon-icon.png"
  BN:
    name: Barnes & Noble
    icon: "/images/icons/barnes-and-noble-icon.png"
  Apple:
    name: Apple Books
    icon: "/images/icons/apple-books-icon.png"
  CFP:
    name: Christian Faith Publishing
    icon: "/images/icons/CFP-logo.png"
sass:
  sass_dir: _sass
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
collections:
  books:
    output: true
    style: compressed
exclude:
- src
