title: Julia Hallmark Christian Fiction
description: Where faith is explored in stories told, and anything is possible!
logo: "images/logo.png"
max_logo_height: 80
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://juliahallmark.com # the base hostname & protocol for your site, e.g. http://example.com
homepage_greeting: Welcome!

# Build settings
plugins:
  - jekyll-feed

collections:
  books:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - src
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
