max_logo_height: 100
timezone: America/Los_Angeles
permalink: '/blog/:year/:slug:output_ext'
vendors:
  Facebook:
    name: Facebook
    icon: /images/icons/facebook-icon.png
    color: blue
  Amazon:
    name: Amazon.com
    icon: /images/icons/amazon-icon.png
    color: yellow
  BN:
    name: Barnes & Noble
    icon: /images/icons/barnes-and-noble-icon.png
    color: green
  Apple:
    name: Apple Books
    icon: /images/icons/apple-books-icon.png
    color: red
  CFP:
    name: Christian Faith Publishing
    icon: /images/icons/CFP-logo.png
    color: black
sass:
  sass_dir: _sass
plugins:
  - jekyll-paginate
paginate_path: '/blog/page:num/'
collections:
  books:
    output: true
    style: compressed
exclude:
  - src
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - tina
  - .forestry
  - .github
title: Be Still and Know Books by Julia Hallmark
description: 'Where faith is explored in stories told, and anything is possible!'
logo: /images/logo.png
background: /images/homepage/mtdiablo2.jpg
url: 'https://juliahallmark.com'
newsletter: ''
patron: ''
paginate: 10
advanced_footer_html: ''
