# Site
name: "Julia Hallmark Christian Fiction"
description: "Where faith is explored in stories told, and anything is possible!"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "authorjuliahallmark@gmail.com"
mailchimp-list: "https://juliahallmark.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
exclude: ["src"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  julia:
    name: Julia
    site: https://juliahallmark.com
    avatar: /assets/images/avatar2.jpg
    bio: "Hi, I'm Julia, the author of The Chase. I hope you like it!"
    email: authorjuliahallmark@gmail.com
    twitter: https://twitter.com/authorjuliahallmark

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: julia
      avatar: /assets/images/avatar2.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
