---
new_page_extension: md
auto_deploy: false
admin_path: "/manage-site/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
# - type: jekyll-pages
#   label: Pages
#   create: documents
- type: books
  label: Books
  create: documents
  templates:
  - book
- type: document
  path: about.md
  label: Profile
  templates:
  - profile
- type: document
  path: _config.yml
  label: Configuration
upload_path: "images/uploads/:year:/:month:/:day:"
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
