---
label: Site Config
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
    min: 3
  label: website title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: logo
  type: file
  config:
    maxSize: 64
  label: logo
- name: url
  type: text
  config:
    required: true
  label: url
- name: homepage_greeting
  type: text
  config:
    required: false
  label: homepage greeting
  description: The salutation that appears on the home page
  default: Welcome!
- name: paginate
  type: number
  label: blog posts per page
  default: 10
- name: newsletter
  type: text
  label: newsletter sign up url
  default: ''
- name: advanced_footer_html
  type: textarea
  label: advanced footer code
  config:
    required: false
    wysiwyg: false
    schema:
      format: html
  default: ''
pages:
- _config.yml
